# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tvolex
service: aws-code-challenge-2025

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-central-1
  memorySize: 256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [TaskProcessingQueue, Arn]

    - Effect: Allow
      Action:
         - sqs:ReceiveMessage
         - sqs:DeleteMessage
         - sqs:GetQueueAttributes
         - sqs:ChangeMessageVisibility
      Resource:
         - Fn::GetAtt: [TaskProcessingQueue, Arn]

    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - Fn::GetAtt: [TaskDLQQueue, Arn]

functions:
  task-gateway:
    role: TaskGatewayRole
    handler: lambda-functions/task-gateway.lambda.js
    events:
      - http:
          path: /api/v1/tasks
          method: POST

  task-processing:
    handler: lambda-functions/task-processing.lambda.js
    role: TaskProcessingRole
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - taskProcessingQueue
              - Arn
          batchSize: 10
    destinations:
      onFailure:
        type: sqs
        arn:
            Fn::GetAtt:
              - taskDLQQueue
              - Arn

  task-dlq:
    handler: lambda-functions/task-dlq.lambda.js
    role: TaskDLQRole
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - taskDLQQueue
              - Arn
          batchSize: 5

resources:
  Resources:
    taskProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: task-processing.fifo
        FifoQueue: true
        VisibilityTimeout: 60
        RedrivePolicy:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region::eu-central-1
                - Ref: AWS::AccountId::650979641201
                - taskDLQQueue
#          Fn::GetAtt:
#            - taskDLQQueue
#            - Arn
          maxReceiveCount: 2

    taskDLQQueue:
        Type: AWS::SQS:Queue
        Properties:
          QueueName: task-dlq.fifo
          FifoQueue: true

    TaskGatewayRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: task-gateway-role
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: [lamda.amazonaws.com]
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SQSSendMessage
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    Fn::GetAtt:
                      - TaskProcessingQueue
                      - Arn

    TaskProcessingRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: task-processing-role
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: [lamda.amazonaws.com]
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SQSProcessing
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                    - sqs:ChangeMessageVisibility
                  Resource:
                    Fn::GetAtt:
                      - TaskProcessingQueue
                      - Arn

    TaskDLQRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: task-dlq-role
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: [lamda.amazonaws.com]
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SQSTaskDLQ
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                  Resource:
                      Fn::GetAtt:
                        - TaskDLQQueue
                        - Arn


package:
  exclude:
    - node_modules/**
    - git/**